---
title: "Quality control of Microarrays for diabetes type 1 dataset"
author: "Selina Ernst"
date: "26 4 2021"
output: html_document
---

# 0.0 libraries

```{r libraries, include=FALSE}
# ------------------------------------------------
# libraries
# ------------------------------------------------

#BiocManager::install()

library(affy)
library(vsn)
library(AnnotationDbi)
library(hgu133plus2hsenstcdf)
library(hgu133plus2hsenstprobe)
library(hexbin)

library(rstudioapi)
library(tidyverse)
```

```{r}
# used for setwd() 

projectPath <- dirname(rstudioapi::getSourceEditorContext()$path)
projectPath

```


# 1.0 Datasets upload

Diabetes type 1 dataset, GSE53454, data is downloaded from the GEO database


```{r}
# ------------------------------------------------
# read CEL files from rawdata/GSE53454 Diabetes type 1
# ------------------------------------------------
setwd(paste(projectPath, "rawdata", "GSE53454 Diabetes type 1", sep = "/"))
data_diabetes <- ReadAffy()


data_diabetes@cdfName <- "HGU133Plus2_Hs_ENST" # changed from "HG-U133_Plus_2"
# changes gene Names: featureNames(data_diabetes) 


diabetes_matrix <- as.data.frame(exprs(data_diabetes))
```


```{r}
# ------------------------------------------------
# understanding of the data sets
# ------------------------------------------------

# how many microarrays are there?
dim(diabetes_matrix)[2]

# how many genes?
dim(diabetes_matrix)[1]

# What are the names of the samples?
colnames(data_diabetes)
substr(colnames(diabetes_matrix), 1,10)

# What does the expression table look like?
head(diabetes_matrix)

# probe set names (or Affymetrix IDs) - are changed when changing cdfName
featureNames(data_diabetes)[1:10]

```

```{r}
# check for NAs or "" 

apply(diabetes_matrix, 2, function(x){sum(is.na(x))})
apply(diabetes_matrix, 2, function(x){sum(x == 0)})
sum(sapply(rownames(diabetes_matrix), function(x){sum(x == "")}))

```



```{r}
setwd(paste(projectPath, "sessions", "rda" ,sep = "/"))
save.image(file = "rawdata_diabetes.rda")

```

# 2.0 Normalization

```{r}
# ------------------------------------------------
# vsnrma normalization
# ------------------------------------------------

diabetes_vsnrma <- vsnrma(data_diabetes)
diabetes_vsnrma_matrix <- exprs(diabetes_vsnrma)


```


```{r}
# ------------------------------------------------
# normalized expression matrix with Ensemble IDs 
# ------------------------------------------------

rownames(diabetes_vsnrma_matrix) <- str_replace(rownames(diabetes_vsnrma_matrix),"\\..*","")  # cuts rownames of at "." 
# "ENST00000000233.10_at"  becomes "ENST00000000233"

diabetes_vsnrma_matrix[60:70,1:2]

```


```{r}
setwd(paste(projectPath, "sessions", "rda" ,sep = "/"))
save.image(file = "rawdata_diabetes.rda")

```


# 3.0 Quality control
## 3.1 Single chip control

```{r}
# ------------------------------------------------
# show microarrays (takes a long time!)
# ------------------------------------------------

setwd(paste(projectPath, "plots", sep = "/"))

for (i in 1:24){
  image(data_diabetes[,i], col = rainbow(100, start = 0, end = 0.75)[100:1])
  file.name = paste0("diabetes_", str_remove(colnames(diabetes_matrix)[i],".CEL"),".pdf")
  # dev.copy2pdf(file = file.name)
}

#----------

setwd(paste(projectPath, "plots", sep = "/"))
par(pty = "s")
image(data_diabetes[,1], col = rainbow(100, start = 0, end = 0.75)[100:1], 
      main = str_remove(colnames(diabetes_matrix)[1],".CEL"))
  file.name = paste0("diabetes_", str_remove(colnames(diabetes_matrix)[1],".CEL"),".pdf")
dev.copy2pdf(file = file.name)



```

## 3.2 pheno data

```{r}
(pData(data_diabetes))
```


# 4.0 Plots
## 4.1 meanSdPlot

```{r}
# ------------------------------------------------
# meanSdPlot of vsnrma normalized data 
# ------------------------------------------------

meanSdPlot(diabetes_vsnrma, plot = FALSE)$gg + theme(aspect.ratio = 1)

setwd(paste(projectPath, "plots", sep = "/"))
dev.copy2pdf(file = "diabetes_meanSdPlot_vsnrma_normalized.pdf")

```


## 4.2 Boxplot

### rawdata

```{r} 
# ------------------------------------------------
# boxplot of rawdata 
# ------------------------------------------------

par(las = 2) #axis labels always perpendicular to the axis

par(mai = c(1.2,0.8,1,0.1))

boxplot(data_diabetes, names = substr(colnames(diabetes_matrix), 1,10),
        col = rainbow(24), cex.axis=0.6, ylab = "Intensity values", 
        main="Gene expression in mircoarrays (beta cell data set: GSE53454)\nbefore vsnrma normalization", 
        horizontal = FALSE)
title(sub = "data is from: (Lopes et al., 2014) ; (Marroqui et al., 2015)", cex.sub = 0.7, line = 4.5)

setwd(paste(projectPath, "plots" ,sep = "/"))
dev.copy2pdf(file = "diabetes_boxplot_rawdata.pdf")

```

### normalized data (vsnrma)

```{r}
# ------------------------------------------------
# boxplot of vsnrma normalized data 
# ------------------------------------------------

par(las = 2)
par(mai = c(1.2,0.8,1,0.1))

boxplot(diabetes_vsnrma_matrix, names = substr(colnames(diabetes_matrix), 1,10),
        col = rainbow(24), cex.axis = 0.6, ylab = "Intensity values",
        main= "Gene expression in mircoarrays (beta cell data set: GSE53454)\nafter vsnrma normalization", 
        horizontal = FALSE, outline = FALSE) # outliers are not drawn
title(sub = "data is from: (Lopes et al., 2014) ; (Marroqui et al., 2015)", cex.sub = 0.7, line = 4.5)

setwd(paste(projectPath, "plots" ,sep = "/"))
dev.copy2pdf(file = "diabetes_boxplot_vsnrma_normalized.pdf") 

```



## 4.3 Histogram
### rawdata

```{r}
# ------------------------------------------------
# histogram of rawdata 
# ------------------------------------------------
par(mai = c(1.2,1,1,0.5))
hist(data_diabetes, 
     col = rainbow(24), 
     main = "Density function of log intensity of beta cells (data set: GSE53454)\nbefore normalization")
title(sub = "data is from: (Lopes et al., 2014) ; (Marroqui et al., 2015)", cex.sub = 0.7, line = 4.5)

setwd(paste(projectPath, "plots" ,sep = "/"))
dev.copy2pdf(file = "diabetes_hist_rawdata.pdf")

```

### normalized (vsnrma)

```{r}
# ------------------------------------------------
# histogram of vsnrma normalized data 
# ------------------------------------------------
par(mai = c(1,1,1,0.5))

plot(density(diabetes_vsnrma_matrix), 
     type = "n", xlab = "log Intensity", ylim = c(0,0.7), 
     main = "Density function of log intensity of beta cells (GSE53454) \n after normalization")

for (i in 1:ncol(diabetes_vsnrma_matrix)){
  lines(density(diabetes_vsnrma_matrix[,i]), col = rainbow(24)[i])
}

setwd(paste(projectPath, "plots" ,sep = "/"))
dev.copy2pdf(file = "diabetes_hist_vsnrma_normalized.pdf")
```

## 4.4 RNA degeneration plot

```{r}
# ------------------------------------------------
# RNA degeneration  
# ------------------------------------------------

rnadeg.raw = AffyRNAdeg(data_diabetes)

# use of shift & scale
par(pty = "s")
plotAffyRNAdeg(rnadeg.raw, col=rainbow(24), transform = "shift.scale")
title(sub = "beta cell data set (GSE53454) rawdata")


setwd(paste(projectPath, "plots" ,sep = "/"))
dev.copy2pdf(file = "diabetes_rnadeg_rawdata.pdf")

# ------------------------------------------------

# use only shift
plotAffyRNAdeg(rnadeg.raw, col = rainbow(24), transform = "shift.only")
title(sub = "beta cell data set (GSE53454) rawdata")


setwd(paste(projectPath, "plots" ,sep = "/"))
dev.copy2pdf(file = "diabetes_rnadegl_rawdata.pdf")

# when lines cross then quality of the chip has to be checked
```

## 4.5 Scatter plot

```{r}
setwd(paste(projectPath, "plots" ,sep = "/"))

par(mai = c(0.8,0.8,0.6,0.1), pty = "s")
for (i in 1:23){
  for (j in (i+1):24){
    plot(diabetes_vsnrma_matrix[,i], diabetes_vsnrma_matrix[,j], pch = ".",
         xlab = substr(colnames(diabetes_matrix), 1,10)[i],
         ylab = substr(colnames(diabetes_matrix), 1,10)[j])
    abline(0,1,col="red")

    title(main = paste("scatterplot of microarrays from beta cell data set (GSE53454) \n", 
                       substr(colnames(diabetes_matrix), 1,10)[i],
                       "and",
                       substr(colnames(diabetes_matrix), 1,10)[j],
                       sep = " ", collapse = NULL))
    
    file.name = paste("diabetes_scatterplot_",
                    substr(colnames(diabetes_matrix), 1,10)[i], 
                    "_",  
                    substr(colnames(diabetes_matrix), 1,10)[i+1], 
                    ".pdf", 
                    sep = "")
    # dev.copy2pdf(file = file.name)
}}

``` 




