---
title: "Analysis of diabetes data set"
author: "Selina Ernst"
date: "2 5 2021"
output: html_document
---

# libraries
```{r libraries, include=FALSE}
# Bioconductor
library(affy)
library(vsn)
library(AnnotationDbi)
library(hgu133plus2hsenstcdf)
library(hgu133plus2hsenstprobe)
library(hexbin)

library(rstudioapi)
library(tidyverse)
library(ggplot2)
library(pheatmap)
library(stats)
```

# expression data sets
```{r}
# ------------------------------------------------
# steps already done in Quality Control
# ------------------------------------------------

projectPath <- dirname(rstudioapi::getSourceEditorContext()$path)
# get CEL files
setwd(paste(projectPath, "rawdata", "GSE53454 Diabetes type 1", sep = "/"))
data_diabetes <- ReadAffy()
# change cdf
data_diabetes@cdfName <- "HGU133Plus2_Hs_ENST"
# create expression matrix
diabetes_matrix <- as.data.frame(exprs(data_diabetes))
# store colnames (microarray)
diabetes_microarray_information <- colnames(diabetes_matrix)
# vsnrm normalization
diabetes_vsnrma <- vsnrma(data_diabetes)
# expression matrix of vsnrm normalized data set
diabetes_vsnrma_matrix <- exprs(diabetes_vsnrma)
# cut rownames at "." ("ENST00000000233.10_at"  becomes "ENST00000000233")
rownames(diabetes_vsnrma_matrix) <- str_replace(rownames(diabetes_vsnrma_matrix),"\\..*","")

```

# information about microarray samples

```{r}
diabetes_microarrays = t(as.data.frame(
  sapply(diabetes_microarray_information, function(x){
    s = str_replace(x,"\\..*","")
    str_split(s, "_")
    })
  ))[,-c(2,3)]
colnames(diabetes_microarrays) <- c("number", "treatment", "time")
rownames(diabetes_microarrays) <- c(1:24)
diabetes_microarrays <- as.data.frame(diabetes_microarrays)

diabetes_microarrays

# replace old IDs sample names
colnames(diabetes_matrix) <- diabetes_microarrays[,"number"]
colnames(diabetes_vsnrma_matrix) <- diabetes_microarrays[,"number"]
rownames(data_diabetes@phenoData) <- diabetes_microarrays[,"number"]
rownames(data_diabetes@protocolData) <- diabetes_microarrays[,"number"]

```

# Processing of data

```{r}
# ------------------------------------------------
# remove control probes from normalized data set
# ------------------------------------------------

diabetes_transcript_names = rownames(diabetes_vsnrma_matrix)

diabetes_vsnrma_matrix = diabetes_vsnrma_matrix[which(!startsWith(diabetes_transcript_names, "AFFX")),] # remove control probes (AFFX) 

dim(diabetes_vsnrma_matrix)
# 95659    24
```

```{r}
# ------------------------------------------------
# convert Affymetrix IDs to gene symbols
# ------------------------------------------------

setwd(paste(projectPath, "rawdata", "tables" ,sep = "/"))
annotation = read.csv("ensemble.103.txt") 
# file comes from www.ensembl.org/biomart

ensemble_genes = annotation[,"Gene.stable.ID"]
ensemble_transcripts  = annotation[,"Transcript.stable.ID"]
ensemble_affyID = annotation[,"AFFY.HG.U133.Plus.2.probe"]
ensemble_symbol = annotation[,"HGNC.symbol"]
```

```{r}
# which transcripts from the microarray are not listed in the ensemble.103.txt file?
diabetes_nomatchesIDs <- rownames(diabetes_vsnrma_matrix)[!(rownames(diabetes_vsnrma_matrix) %in% ensemble_transcripts)]
length(diabetes_nomatchesIDs)
# 112

# remove these 112 transcripts from expression data
diabetes_vsnrma_matrix <- diabetes_vsnrma_matrix[rownames(diabetes_vsnrma_matrix) %in% ensemble_transcripts,]
dim(diabetes_vsnrma_matrix)
# 95547    24
```

```{r}
# ------------------------------------------------
# select only those symbols that are in the diabetes data set
# ------------------------------------------------

names(ensemble_symbol) <- ensemble_transcripts 
diabetes_symbol <- ensemble_symbol[rownames(diabetes_vsnrma_matrix)]
# symbols already in right order vor diabetes_vsnrma_matrix

# ------------------------------------------------
# name the probes according to gene symbol
# ------------------------------------------------

rownames(diabetes_vsnrma_matrix) <- as.character(diabetes_symbol)


head(diabetes_vsnrma_matrix)[,1:2]
```

```{r}
# check for NAs or "" 

#apply(diabetes_vsnrma_matrix, 2, function(x){sum(x == 0)})

sum(sapply(rownames(diabetes_vsnrma_matrix), function(x){sum(is.na(x))})) # 0 are NA

sum(sapply(rownames(diabetes_vsnrma_matrix), function(x){sum(x == "", na.rm = TRUE)})) # 1096 are ""

```

```{r}
# alphabetical order
diabetes_vsnrma_matrix <- as.data.frame(diabetes_vsnrma_matrix)
diabetes_GeneExprs = diabetes_vsnrma_matrix[order(rownames(diabetes_vsnrma_matrix)),]
head(diabetes_GeneExprs)
dim(diabetes_GeneExprs)
```


```{r}
# get the tissue specifc genes from TRA Daten
setwd(paste(projectPath, "rawdata", "tables" ,sep = "/"))
pancreas_specific_genes = read.csv("pancreas_specific_genes_human.csv")

# create a expression matrix with only those genes
diabetes_GeneExprs_sub = diabetes_GeneExprs[which(rownames(diabetes_GeneExprs) %in% pancreas_specific_genes),]
dim(diabetes_GeneExprs_sub) 
(diabetes_GeneExprs_sub)
# have to check again if everything makes sense here 

diabetes_vsnrma_matrix_sub = diabetes_vsnrma_matrix[which(rownames(diabetes_vsnrma_matrix) %in% pancreas_specific_genes),]
dim(diabetes_vsnrma_matrix_sub)
```

# plots

```{r}
pheatmap(t(diabetes_GeneExprs_sub), 
         labels_row = paste(diabetes_microarrays[,"time"],",",diabetes_microarrays[,"treatment"]),
         labels_col = rep("",nrow(diabetes_GeneExprs_sub)))


```

```{r}
# ------------------------------------------------
# small boxplot (shows only small part of the genes)
# ------------------------------------------------

par(las = 2)

boxplot(t(diabetes_vsnrma_matrix_sub)[,1:30],
         col = rainbow(100),
         main="", 
         horizontal = FALSE)

```



