---
title: "Pancreas Quality Control"
author: "Bianca Greul"
date: "28 4 2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## R Markdown


### 1. Reading in pancreas data

PDAC (pancreatic cancer) data set, GSE59761, downloaded from GEO database

```{r}
library(affy)
library(vsn)

projectPath <- dirname(rstudioapi::getSourceEditorContext()$path)
projectPath

setwd(paste(projectPath, "rawdata", "GSE59761 PDAC Capan-1 Zellen", sep = "/"))
data_pancreas <- ReadAffy()


## Normalization

pancreas_vsnrma <- vsnrma(data_pancreas)

pancreas_vsnrma_matrix <- exprs(pancreas_vsnrma)
head(pancreas_vsnrma_matrix)
```

```{r}
setwd(paste(projectPath, "sessions", "rda" ,sep = "/"))
save.image(file = "rawdata.pancreas.rda")
```

```{r}
## Overview of dataset

summary(data_pancreas)
str(data_pancreas)

pancreas_chips_number <- length(colnames(pancreas_vsnrma_matrix))
pancreas_chips_names <- colnames(pancreas_vsnrma_matrix)
```


### 2. Quality control: Single chip control

```{r}
## Quality control in pdf

setwd(paste(projectPath, "plots", sep = "/"))

par(pty = "s")

for (i in 1:6){

  image(data_pancreas[,i], col = rainbow(100, start = 0, end = 0.75)[100:1])
  
  file.name <- paste(as.character(substr(pancreas_chips_names [i], 1, nchar(pancreas_chips_names [i])-4)),".pdf",
                    sep = "")
  
  #dev.copy2pdf(file = file.name)
  
}

## all chips are fully functional

```


### 3. Renaming files

```{r}
## Remove ending from file names

pData(data_pancreas)

filenames <- rownames(pData(data_pancreas)) 
pancreas_samples <- substr(filenames, 1, 10)
pancreas_samples
```


### 4. Plots

#### Boxplots

```{r}
## Rawdata

par(las = 2)
par(mai = c(1.2,0.8,1,0.1))

boxplot(data_pancreas, names = pancreas_samples, col = rainbow(6), main = "Gene expression in mircoarrays (PDAC data set: GSE59761)\nbefore normalization", cex.axis=0.6, ylab = "Intensity values")
title(sub = "data from: (Stoy et al., 2015)", cex.sub = 0.7, line = 4.5)

setwd(paste(projectPath, "plots" ,sep = "/"))
dev.copy2pdf(file = "pancreas_boxplot_rawdata.pdf")
```

```{r}
## Normalized data

par(las = 2)
par(mai = c(1.2,0.8,1,0.1))

boxplot(data_pancreas, names = pancreas_samples, col = rainbow(6), main = "Gene expression in mircoarrays (PDAC data set: GSE59761)\nafter normalization", cex.axis=0.6, ylab = "Intensity values")
title(sub = "data from: (Stoy et al., 2015)", cex.sub = 0.7, line = 4.5)

setwd(paste(projectPath, "plots" ,sep = "/"))
dev.copy2pdf(file = "pancreas_boxplot_vsnrma_normalized.pdf")
```

#### MeanSdPlot

```{r}
meanSdPlot(pancreas_vsnrma, plot = FALSE)$gg + theme(aspect.ratio = 1) 

setwd(paste(projectPath, "plots", sep = "/"))
dev.copy2pdf(file = "pancreas_meanSdPlot_vsnrma_normalized.pdf")
```

#### Histogram

```{r}
## Rawdata

par(mai = c(1.2,1,1,0.5))
hist(data_pancreas, col = rainbow(6), main = "Density function of log intensity of PDAC cells (data set: GSE59761)\nbefore normalization")
title(sub = "data from: (Stoy et al., 2015)", cex.sub = 0.7, line = 4.5)


setwd(paste(projectPath, "plots", sep = "/"))
dev.copy2pdf(file = "pancreas_hist_rawdata.pdf")

```

```{r}
## Normalized

par(mai = c(1.2,1,1,0.5))
plot(density(pancreas_vsnrma_matrix[,1]), type = "n", xlab = "log intensity", main = "Density function of log intensity of PDAC cells (data set: GSE59761)\nafter normalization", ylim = c(0,0.4))
title(sub = "data from: (Stoy et al., 2015)", cex.sub = 0.7, line = 4.5)

for (i in 1:ncol(pancreas_vsnrma_matrix)){
  lines(density(pancreas_vsnrma_matrix[,i]), col = rainbow(6)[i])
}

setwd(paste(projectPath, "plots" ,sep = "/"))
dev.copy2pdf(file = "pancreas_hist_vsnrma_normalized.pdf")

```

#### RNA Degradation 

```{r}

RNAdeg_PDAC <- AffyRNAdeg(data_pancreas)

## shift and scale
par(pty = "s", mai = c(1.4,0.5,0.5,0.1))
plotAffyRNAdeg(RNAdeg_PDAC, col = rainbow(6))
title(sub = "PDAC data set (GSE59761) rawdata")

setwd(paste(projectPath, "plots" ,sep = "/"))
dev.copy2pdf(file = "pancreas_rnadeg_shiftt_scale_rawdata.pdf")

## shift
par(pty = "s", mai = c(1.4,0.5,0.5,0.1))
plotAffyRNAdeg(RNAdeg_PDAC, col = rainbow(6), transform = "shift.only")
title(sub = "PDAC data set (GSE59761) rawdata")

dev.copy2pdf(file = "pancreas_rnadeg_shift_rawdata.pdf")

## No crossing of lines. Quality of the chips is good.
```

#### Scatter plot

```{r}
setwd(paste(projectPath, "plots" ,sep = "/"))

par(mai = c(0.8,0.8,0.6,0.1), pty = "s")

for (i in 1:5) {
  for (j in (i+1):6){
    plot(pancreas_vsnrma_matrix[,i], pancreas_vsnrma_matrix[,j], pch = ".",
         xlab = pancreas_samples[i],
         ylab = pancreas_samples[j])
    abline(0, 1, col = "red")
  
    title(main = paste("Scatterplot of microarrays\n", 
                       pancreas_samples[i],
                       "and",
                       pancreas_samples[j],
                       sep = " ", collapse = NULL))
    
    file.name = paste("pancreas_scatterplot_",
                      pancreas_samples[i], 
                      "_",  
                      pancreas_samples[j], 
                      ".pdf", 
                      sep = "")
  
  # dev.copy2pdf(file = file.name)

}}

```